import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "./provider/query";
import AuthProvider from "./provider/auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="min-h-screen flex flex-col">
          <header className="bg-gray-800 text-white p-4">
            <div className="container mx-auto">
              <h1 className="text-3xl font-bold">GRP</h1>
            </div>
          </header>
          <main className="flex-grow">
            <AuthProvider>
              <Providers>{children}</Providers>
            </AuthProvider>
          </main>
          <footer className="bg-gray-800 text-white p-4 text-center">
            <div className="container mx-auto">
              <p>&copy; 2024 GitHub Repo Recommender. All rights reserved.</p>
            </div>
          </footer>
        </div>
      </body>
    </html>
  );
}
